### ISSUE TITLE
how to add this to a map

### ISSUE THREAD

**Issue by thebikwirm** [FarmingAgency/FS22_TerraLifePlus_Documentation#12]
I do not see a wiki, would like to add to a map not on modhub
got any info on how to do it?

**Comment by Timmeey86** [comment]
Hi, there are some regulations on integrating Terra Life Plus into another map:

- If you are the map author and you want to publish the map with terra life plus, the only way allowed to do so is through publishing it through the Farming Agency Charity account. Any money earned will be donated to the German Cancer Aid. If you agree to these terms, we can get in touch and support you in adding it in.
- If you are not the map author, then you may not publish it anywhere. You can modify the map for personal use, but you won't get any support since we simply don't have the capacity to do so. Integrating TLP into a map is a complex task.

**Comment by thebikwirm** [comment]
doesnt matter now, more or less got told to fuck off, cause its too difficult and its not my map
